<header id="header">
	<div class="container-fluid header-logo-container">
		<div class="big-logo-container">
			<a href="#" class="main-logo-big"></a>
		</div>
	</div>
	<div class="sticky-header-container">
		<div class="container-fluid logo-menu-search-container">
			<div class="logo-container"><a href="#" class="main-logo"></a></div>
			<div class="menu-container">
				<ul class="main-menu">
					<li><a href="#food">Food</a></li>
					<li><a href="#people">People</a></li>
					<li><a href="#travel">Travel</a></li>
					<li><a href="#events">Events</a></li>
					<li><a href="#videos">Videos</a></li>
				</ul>
			</div>
			<div class="search-container">
				<a href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
			</div>		
		</div>
		<div class="container dropdown-menu-container">
			<div id="events" class="all-dropdown row">				
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-1.png" class="img-responsive" alt="">
							<span>Competition</span>
						</div>
						<div class="text-container">
							<p>Semi-Finals Happening at Savour Wines This September!</p>
						</div>
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-2.png" class="img-responsive" alt="">
							<span>Coming Soon</span>
						</div>
						<div class="text-container">
							<p>Taste over 400 varieties of wines at the SAVOUR Global Wine Market</p>
						</div>
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-3.png" class="img-responsive" alt="">
							<div class="play-icon"></div>
						</div>
						<div class="text-container">
							<p>Chef Bjorn Shen & Jonathan Lee Share Their Experience at Savour...</p>
						</div>						
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-4.png" class="img-responsive" alt="">
						</div>
						<div class="text-container">
							<p>A Fair to Savour: Masterchefs, New Menus and Live Music</p>
						</div>
					</a>
				</div>
				<a href="#" class="view-all">View All <i class="fa fa-chevron-down" aria-hidden="true"></i></a>
			</div>
			<div id="videos" class="all-dropdown row">				
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-4.png" class="img-responsive" alt="">
							<span>Competition</span>
						</div>
						<div class="text-container">
							<p>Semi-Finals Happening at Savour Wines This September!</p>
						</div>
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-3.png" class="img-responsive" alt="">
							<span>Coming Soon</span>
						</div>
						<div class="text-container">
							<p>Taste over 400 varieties of wines at the SAVOUR Global Wine Market</p>
						</div>
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-2.png" class="img-responsive" alt="">
							<div class="play-icon"></div>
						</div>
						<div class="text-container">
							<p>Chef Bjorn Shen & Jonathan Lee Share Their Experience at Savour...</p>
						</div>						
					</a>
				</div>
				<div class="col-md-3">
					<a href="#">
						<div class="img-container">
							<img src="assets/images/menu/menu-content-1.png" class="img-responsive" alt="">
						</div>
						<div class="text-container">
							<p>A Fair to Savour: Masterchefs, New Menus and Live Music</p>
						</div>
					</a>
				</div>
				<a href="#" class="view-all">View All <i class="fa fa-chevron-down" aria-hidden="true"></i></a>
			</div>
		</div>
	</div>
</header>